export const metadata = {
  title: "About Next",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      <h1 className="font-bold text-2xl text-gray-600">About</h1>
      <div className="py-4 text-gray-600">
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Quas dolorum
          culpa molestiae saepe ex. Expedita nesciunt aspernatur sint quisquam
          iusto rem commodi dicta, reprehenderit iste quo sequi incidunt id
          laboriosam minus ex harum culpa! Architecto veritatis numquam
          eligendi. In ipsa quae sequi minus corporis. Sint tenetur illo debitis
          blanditiis dolorem?
        </p>
      </div>
    </div>
  );
}
