import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./partials/Sidebar";
import Content from "./partials/Content";
import Footer from "./partials/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex w-full h-screen">
          <Sidebar />
          <div className="right-container p-4 w[78%] overflow-scroll">
            <Content>{children}</Content>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
